export const GET_ARTWORKS = 'GET_ARTWORKS';
export const GET_ARTISTS = 'GET_ARTISTS';
export const GET_GENRES = 'GET_GENRES';
export const FILTER_ARTWORKS_ARTIST = 'FILTER_ARTWORKS_ARTIST';
export const FILTER_ARTWORKS_GENRE = 'FILTER_ARTWORKS_GENRE';
